language: java

jdk:
  - openjdk8
  
branches:
  only:
    - master
    - stable-core
    - stable
    
install: true

script: 
  - if [ $TRAVIS_BRANCH == "stable-core" ]; then gradle :ili2c-core:jar ; fi 
  - if [ $TRAVIS_BRANCH != "stable-core" ]; then gradle jar ; fi

deploy:
  - provider: script
    skip_cleanup: true
    script: gradle -Duser.repos_pwd=${repos_pwd} -Duser.repos_usr=jql_jars-INTE  bindist uploadArchives
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    script: gradle -Duser.repos_pwd=${repos_pwd} -Duser.repos_usr=jql_jars-INTE -Drelease=final bindist uploadArchives
    on:
      branch: stable
  - provider: script
    skip_cleanup: true
    script: gradle -Duser.repos_pwd=${repos_pwd} -Duser.repos_usr=jql_jars-INTE -Drelease=final :ili2c-core:uploadArchives
    on:
      branch: stable-core
notifications:
  email:
    on_success: change # default: change
    on_failure: always # default: always