language: java

jdk:
  - openjdk8

addons:
  ssh_known_hosts:
  - ftp.interlis.ch

branches:
  only:
    - master
    - stable-core
    - stable

install: true

script: 
  - if [ $TRAVIS_BRANCH == "stable-core" ]; then ./gradlew :ili2c-core:jar :ili2c-core:test ; fi 
  - if [ $TRAVIS_BRANCH != "stable-core" ]; then ./gradlew jar test ; fi
  
deploy:
  - provider: script
    skip_cleanup: true
    script: ./gradlew --info -Drepos_dir=${repos_dir} -Drepos_pwd=${repos_pwd} -Drepos_usr=${repos_usr}  bindist uploadArchives
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    script: ./gradlew -Drepos_dir=${repos_dir} -Drepos_pwd=${repos_pwd} -Drepos_usr=${repos_usr} '-Drelease=' bindist uploadArchives uploadBindist
    on:
      branch: stable
  - provider: script
    skip_cleanup: true
    script: ./gradlew -Drepos_dir=${repos_dir} -Drepos_pwd=${repos_pwd} -Drepos_usr=${repos_usr} '-Drelease=' :ili2c-core:uploadArchives
    on:
      branch: stable-core
notifications:
  email:
    on_success: change # default: change
    on_failure: always # default: always